name: deploy-myblog
on:
  push:
    branches:
      - main # 针对的是main分支
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3 # 第三方的action 作用：拉取代码
      - name: set id_rsa # 创建文件夹
        run: | # ssh-keyscan 121.41.4.7 >> ~/.ssh/known_hosts 把自己的服务器地址加入到当前虚拟机的信任域名里面
          mkdir -p ~/.ssh/
          echo "${{ secrets.MY_ID_RSA }}" > ~/.ssh/id_rsa
          chmod 600  ~/.ssh/id_rsa
          ssh-keyscan 121.41.4.7 >> ~/.ssh/known_hosts
      - name: deploy # 自动发布
        run: |
          ssh root@121.41.4.7 "
           # 注意：服务器已经克隆代码到 /root/myblog/imooc-320-html 目录

           cd /root/myblog/imooc-320-html;
           touch aaa.txt;

           # 重启服务
          "
      - name: delete id_rsa
        run: rm -rf ~/.ssh/id_rsa